"""Default source catalog for hourly content research collection."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any


MVP_COLLECTION_SOURCE_IDS = frozenset(
    {
        "naver_news",
        "newsapi",
        "nytimes",
        "ecos",
        "kosis",
        "opendart",
        "fred",
        "eia",
        "un_comtrade",
    }
)


@dataclass(frozen=True)
class CollectionSource:
    source_id: str
    display_name: str
    category: str
    adapter: str
    access_method: str
    default_body_tier: int
    cadence_minutes: int = 60
    enabled: bool = True
    priority: int = 50
    notes: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


DEFAULT_COLLECTION_SOURCES: tuple[CollectionSource, ...] = (
    CollectionSource(
        source_id="naver_news",
        display_name="Naver News Search API",
        category="korean_news_discovery",
        adapter="content_research.sources.news_discovery.naver_news",
        access_method="api",
        default_body_tier=0,
        priority=10,
        notes="Korean news metadata, original links, snippets, and publication times.",
    ),
    CollectionSource(
        source_id="korea_policy_rss",
        display_name="Korea Policy Briefing RSS",
        category="korean_official_policy",
        adapter="news_discovery.policy_briefing_rss",
        access_method="rss",
        default_body_tier=3,
        priority=15,
        notes="Government policy news and releases for official confirmation.",
    ),
    CollectionSource(
        source_id="bigkinds",
        display_name="BIGKinds",
        category="korean_news_archive",
        adapter="news_discovery.bigkinds",
        access_method="api_or_licensed_service",
        default_body_tier=0,
        priority=30,
        notes="Korean media archive; body use depends on agreement or NewsStore rights.",
    ),
    CollectionSource(
        source_id="gdelt_doc",
        display_name="GDELT DOC 2.0",
        category="international_news_discovery",
        adapter="news_discovery.gdelt",
        access_method="api",
        default_body_tier=0,
        priority=10,
        notes="Global multilingual article discovery and trend detection.",
    ),
    CollectionSource(
        source_id="newsapi",
        display_name="NewsAPI",
        category="international_news_discovery",
        adapter="content_research.sources.news_discovery.newsapi",
        access_method="api",
        default_body_tier=0,
        priority=25,
        notes="Supplementary discovery; anti-republication terms apply.",
    ),
    CollectionSource(
        source_id="nytimes",
        display_name="The New York Times",
        category="international_publisher",
        adapter="content_research.sources.news_discovery.nytimes",
        access_method="api",
        default_body_tier=0,
        priority=20,
        notes="Use Article Search/Top Stories metadata, abstracts, lead paragraphs, and URLs.",
    ),
    CollectionSource(
        source_id="guardian",
        display_name="The Guardian Open Platform",
        category="paid_international_publisher",
        adapter="news_discovery.guardian",
        access_method="commercial_or_rights_managed_api",
        default_body_tier=0,
        priority=20,
        notes="Treat as paid/licensed for this project; no body collection until commercial terms are registered.",
    ),
    CollectionSource(
        source_id="reuters_lseg",
        display_name="Reuters via LSEG",
        category="licensed_international_news",
        adapter="licensed_news.reuters_lseg",
        access_method="licensed_api",
        default_body_tier=2,
        priority=15,
        notes="Enterprise entitlement required before body collection.",
    ),
    CollectionSource(
        source_id="associated_press",
        display_name="Associated Press",
        category="licensed_international_news",
        adapter="licensed_news.associated_press",
        access_method="licensed_api",
        default_body_tier=2,
        priority=25,
        notes="Use only with AP contract/API entitlement.",
    ),
    CollectionSource(
        source_id="bloomberg",
        display_name="Bloomberg Data License",
        category="licensed_business_news",
        adapter="licensed_news.bloomberg_data_license",
        access_method="licensed_api_or_sftp",
        default_body_tier=2,
        priority=25,
        notes="Enterprise license required for news/data delivery.",
    ),
    CollectionSource(
        source_id="dow_jones_wsj",
        display_name="Dow Jones / Wall Street Journal",
        category="licensed_business_news",
        adapter="licensed_news.dow_jones",
        access_method="licensed_api",
        default_body_tier=2,
        priority=25,
        notes="Subscription entitlement required; includes WSJ/Dow Jones depending on package.",
    ),
    CollectionSource(
        source_id="ft",
        display_name="Financial Times",
        category="international_business_news",
        adapter="licensed_news.financial_times",
        access_method="licensed_api_or_domain_monitor",
        default_body_tier=0,
        priority=30,
        notes="Metadata-only until licensed access is registered.",
    ),
    CollectionSource(
        source_id="economist",
        display_name="The Economist",
        category="international_analysis",
        adapter="news_discovery.publisher_domain_monitor",
        access_method="domain_monitor",
        default_body_tier=0,
        priority=35,
        notes="Use for issue discovery and context triangulation; default metadata-only.",
    ),
    CollectionSource(
        source_id="bbc",
        display_name="BBC News",
        category="international_public_media",
        adapter="news_discovery.publisher_rss",
        access_method="rss_or_domain_monitor",
        default_body_tier=0,
        priority=35,
        notes="Use headline, summary, URL, and publisher time.",
    ),
    CollectionSource(
        source_id="cnn",
        display_name="CNN / CNN Business",
        category="international_news",
        adapter="news_discovery.publisher_rss",
        access_method="rss_or_domain_monitor",
        default_body_tier=0,
        priority=40,
        notes="RSS terms are restrictive; default metadata-only.",
    ),
    CollectionSource(
        source_id="cnbc",
        display_name="CNBC",
        category="international_business_news",
        adapter="news_discovery.publisher_domain_monitor",
        access_method="domain_monitor",
        default_body_tier=0,
        priority=40,
        notes="Useful business/economy radar; avoid investment signal framing.",
    ),
    CollectionSource(
        source_id="npr",
        display_name="NPR",
        category="international_public_media",
        adapter="news_discovery.publisher_rss",
        access_method="rss_or_authorized_cds_api",
        default_body_tier=0,
        priority=45,
        notes="CDS API requires authorization; RSS is summary/link first.",
    ),
    CollectionSource(
        source_id="washington_post",
        display_name="The Washington Post",
        category="international_publisher",
        adapter="news_discovery.publisher_rss",
        access_method="rss_or_domain_monitor",
        default_body_tier=0,
        priority=45,
        notes="Use RSS/domain metadata unless special permission exists.",
    ),
    CollectionSource(
        source_id="politico",
        display_name="POLITICO",
        category="policy_news",
        adapter="news_discovery.publisher_rss",
        access_method="rss_or_domain_monitor",
        default_body_tier=0,
        priority=45,
        notes="Strong policy radar source; licensed products can be added later.",
    ),
    CollectionSource(
        source_id="axios",
        display_name="Axios",
        category="policy_business_tech_news",
        adapter="news_discovery.publisher_rss",
        access_method="rss_or_domain_monitor",
        default_body_tier=0,
        priority=45,
        notes="Fast issue radar; verify elsewhere before brief use.",
    ),
    CollectionSource(
        source_id="foreign_affairs",
        display_name="Foreign Affairs",
        category="geopolitical_analysis",
        adapter="news_discovery.publisher_rss",
        access_method="rss_or_domain_monitor",
        default_body_tier=0,
        priority=50,
        notes="Analysis source, not primary fact source.",
    ),
    CollectionSource(
        source_id="le_monde",
        display_name="Le Monde",
        category="europe_news",
        adapter="news_discovery.publisher_rss",
        access_method="rss",
        default_body_tier=0,
        priority=50,
        notes="RSS use is restricted; default metadata-only.",
    ),
    CollectionSource(
        source_id="nikkei_asia",
        display_name="Nikkei Asia",
        category="asia_business_news",
        adapter="news_discovery.publisher_rss",
        access_method="rss",
        default_body_tier=0,
        priority=35,
        notes="Asia economy, supply chain, and tech radar; default metadata-only.",
    ),
    CollectionSource(
        source_id="al_jazeera",
        display_name="Al Jazeera",
        category="global_south_geopolitics",
        adapter="news_discovery.publisher_domain_monitor",
        access_method="domain_monitor",
        default_body_tier=0,
        priority=45,
        notes="Useful for Middle East and Global South perspective; verify conflict claims.",
    ),
    CollectionSource(
        source_id="dw",
        display_name="Deutsche Welle",
        category="europe_public_media",
        adapter="news_discovery.publisher_rss",
        access_method="rss",
        default_body_tier=0,
        priority=50,
        notes="Europe and global public media perspective.",
    ),
    CollectionSource(
        source_id="ecos",
        display_name="Bank of Korea ECOS",
        category="korean_official_data",
        adapter="content_research.sources.official_data.ecos",
        access_method="api",
        default_body_tier=3,
        priority=10,
        notes="Korean macro and financial statistics.",
    ),
    CollectionSource(
        source_id="kosis",
        display_name="KOSIS OpenAPI",
        category="korean_official_data",
        adapter="content_research.sources.official_data.kosis",
        access_method="api",
        default_body_tier=3,
        priority=10,
        notes="Korean official statistics.",
    ),
    CollectionSource(
        source_id="opendart",
        display_name="OpenDART",
        category="korean_filing_data",
        adapter="content_research.sources.official_data.opendart",
        access_method="api",
        default_body_tier=3,
        priority=20,
        notes="Korean corporate filings and disclosures.",
    ),
    CollectionSource(
        source_id="worldbank",
        display_name="World Bank Indicators",
        category="international_official_data",
        adapter="official_data.worldbank",
        access_method="api",
        default_body_tier=3,
        priority=20,
        notes="Global development and macro indicators.",
    ),
    CollectionSource(
        source_id="imf",
        display_name="IMF Data",
        category="international_official_data",
        adapter="official_data.imf",
        access_method="api",
        default_body_tier=3,
        priority=20,
        notes="Global macro, WEO, finance, and exchange-rate data.",
    ),
    CollectionSource(
        source_id="oecd",
        display_name="OECD Data API",
        category="international_official_data",
        adapter="official_data.oecd",
        access_method="api",
        default_body_tier=3,
        priority=25,
        notes="OECD indicators via SDMX.",
    ),
    CollectionSource(
        source_id="fred",
        display_name="FRED API",
        category="us_official_data",
        adapter="content_research.sources.official_data.fred",
        access_method="api",
        default_body_tier=3,
        priority=25,
        notes="US macro and financial time series.",
    ),
    CollectionSource(
        source_id="eia",
        display_name="U.S. Energy Information Administration API",
        category="us_energy_data",
        adapter="content_research.sources.official_data.eia",
        access_method="api",
        default_body_tier=3,
        priority=25,
        notes="Oil, gas, electricity, and energy inventory time series.",
    ),
    CollectionSource(
        source_id="un_comtrade",
        display_name="UN Comtrade",
        category="international_trade_data",
        adapter="content_research.sources.official_data.un_comtrade",
        access_method="api",
        default_body_tier=3,
        priority=25,
        notes="Trade flow verification.",
    ),
)
